[workspace]
members = ["server"]
resolver = "3"

[workspace.package]
version = "0.0.1"
license = "MIT"
authors = ["Simon Blum"]
edition = "2024"
description = ""
repository = ""

[workspace.dependencies]
