services:
  backend:
    image: definitelynotsimon13/dividi-backend:latest
   # depends_on:
    #   - redis
    environment:
      RUST_LOG: "trace"

  frontend:
    image: definitelynotsimon13/dividi-frontend:latest
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dividi.hauptspeicher.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  # redis:
  #   image: redis:7.4.2-alpine
  #   restart: always
  #   volumes: 
  #     - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  #     - cache:/data
  #   environment:
  #     - REDIS_PASSWORD=password
  #     - REDIS_PORT=6379

  reverse-proxy:
    image: traefik:v3.3
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=simon21.blum@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

volumes:
  letsencrypt:
  cache:
    driver: local
  redisinsight:
    driver: local

