services:
  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.backend
  #   depends_on:
  #     - redis
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     RUST_LOG: "trace"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.docker.localhost`)"

  # redis:
  #   image: redis:7.4.2-alpine
  #   restart: always
  #   ports: 
  #     - '6379:6379'
  #   volumes: 
  #     - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  #     - cache:/data
  #   environment:
  #     - REDIS_PASSWORD=password
  #     - REDIS_PORT=6379
  #
  # redisinsight:
  #   image: redis/redisinsight:latest
  #   restart: always
  #   ports:
  #     - '5540:5540'
  #   volumes:
  #     - redisinsight:/data


#   reverse-proxy:
#     image: traefik:v3.3
#     command: --api.insecure=true --providers.docker
#     ports:
#       - "80:80"
#       - "8080:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#
# volumes:
#   cache:
#     driver: local
#   redisinsight:
#     driver: local

