FROM node:23-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve the built assets with Nginx
FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /etc/nginx/conf.d/*

COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /var/www/dividi

CMD ["nginx", "-g", "daemon off;"]
